/**
 * POI locations SSOT (reakmapping §1·§3). WGS84 decimal degrees, 6dp.
 */

import type { PoiLocation } from "./poiTypes"

export const POI_LOCATIONS: ReadonlyArray<PoiLocation> = [
  {
    id: "agi-jetty",
    code: "AGI",
    name: "AGI – Al Ghallan Island (Jetty 대표)",
    category: "HVDC_SITE",
    latitude: 24.841096,
    longitude: 53.658619,
    summary: "HVDC Site - Jetty (rep.)",
    priority: 900,
    tags: ["HVDC", "site"],
    displayLabel: "AGI",
  },
  {
    id: "das-island",
    code: "DAS",
    name: "DAS – Das Island(섬 중심)",
    category: "HVDC_SITE",
    latitude: 25.1477,
    longitude: 52.875,
    summary: "HVDC Site - Island",
    priority: 890,
    tags: ["HVDC", "site"],
    displayLabel: "DAS",
  },
  {
    id: "mirfa-iwpp",
    code: "MIR",
    name: "MIR – Mirfa IWPP(플랜트)",
    category: "HVDC_SITE",
    latitude: 24.11885,
    longitude: 53.44436,
    summary: "HVDC Site - IWPP",
    priority: 880,
    tags: ["HVDC", "site"],
    displayLabel: "MIR",
  },
  {
    id: "shuweihat-complex",
    code: "SHU",
    name: "SHU – Shuweihat Complex(단지 중심)",
    category: "HVDC_SITE",
    latitude: 24.16017,
    longitude: 52.57292,
    summary: "HVDC Site - Complex",
    priority: 870,
    tags: ["HVDC", "site"],
    displayLabel: "SHU",
  },
  {
    id: "dsv-mussafah-office-m19",
    code: "DSV-M19",
    name: "DSV Mussafah 사무실(M-19)",
    category: "OFFICE",
    latitude: 24.366698,
    longitude: 54.476102,
    summary: "Office - DSV (M-19)",
    priority: 800,
    tags: ["DSV", "office"],
    displayLabel: "DSV OFFICE",
  },
  {
    id: "dsv-inland-warehouse-m44",
    code: "DSV-WH",
    name: "DSV Inland Warehouse (M-44)",
    category: "WAREHOUSE",
    latitude: 24.347077,
    longitude: 54.47772,
    summary: "Warehouse - DSV Inland WH",
    priority: 820,
    tags: ["DSV", "warehouse"],
    displayLabel: "DSV WAREHOUSE",
  },
  {
    id: "mosb-yard",
    code: "MOSB-YARD",
    name: "MOSB YARD",
    category: "YARD",
    latitude: 24.331414,
    longitude: 54.456911,
    summary: "Yard - MOSB YARD",
    priority: 780,
    tags: ["MOSB", "yard"],
    displayLabel: "MOSB YARD",
  },
  {
    id: "mosb-sct-office",
    code: "MOSB-SCT",
    name: "MOSB-SCT Office",
    category: "OFFICE",
    latitude: 24.32479,
    longitude: 54.46685,
    displayJitter: [-0.00018, -0.00012],
    labelOffsetPx: [0, -18],
    summary: "Office - MOSB-SCT",
    priority: 775,
    tags: ["MOSB", "office", "sct"],
    displayLabel: "MOSB-SCT",
  },
  {
    id: "zayed-port",
    code: "MZP",
    name: "Mina Zayed Port(대표)",
    category: "PORT",
    latitude: 24.52489,
    longitude: 54.37798,
    summary: "Port - Zayed",
    priority: 860,
    tags: ["port"],
    displayLabel: "MZP",
  },
  {
    id: "khalifa-port-kpct",
    code: "KPP",
    name: "Khalifa Port – KPCT",
    category: "PORT",
    latitude: 24.8095,
    longitude: 54.64842,
    summary: "Port - Khalifa (KPCT)",
    priority: 850,
    tags: ["port", "KPCT"],
    displayLabel: "KPP",
  },
  {
    id: "auh-airport",
    code: "AUH",
    name: "Abu Dhabi(Zayed) International Airport – AUH",
    category: "AIRPORT",
    latitude: 24.441,
    longitude: 54.6492,
    summary: "Airport - AUH",
    priority: 840,
    tags: ["airport"],
    displayLabel: "AUH",
  },
]

export function getPoiById(id: string): PoiLocation | undefined {
  return POI_LOCATIONS.find((p) => p.id === id)
}

export function getPoiByCode(code: string): PoiLocation | undefined {
  const key = code.trim().toLowerCase()
  return POI_LOCATIONS.find((p) => p.code.toLowerCase() === key)
}
